name: CD

on:
  push:
    branches: main

jobs:
  deocker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout code
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Trivy scanner for Base Image
      run: |
        dockerImageName=$(awk 'NR==1 {print $2}' Dockerfile)
        echo $dockerImageName
        docker run --rm -v $WORKSPACE:/root/.cache/ aquasec/trivy:0.32.1 $dockerImageName

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/webserver:${{ github.sha }}

    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: 'docker.io/${{secrets.DOCKERHUB_USERNAME}}/webserver:${{ github.sha }}'
    #     format: 'table'
    #     exit-code: '1'
    #     ignore-unfixed: true
    #     vuln-type: 'os,library'
    #     severity: 'CRITICAL'
  
